/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M4A3oividNb
 */
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

export function Paraphrase() {
  return (
    <div className="m-auto w-full max-w-4xl rounded-lg dark:bg-[#262626] bg-white p-6 shadow-lg">
      <div className="mb-4 flex items-center space-x-2">
        <Button className="rounded-md px-4 py-2 " variant="secondary">
          Standard
        </Button>
        <Button className="rounded-md px-4 py-2" variant="outline">
          Fluency
        </Button>
        <Button className="rounded-md px-4 py-2" variant="outline">
          Formal
        </Button>
        <Button className="rounded-md px-4 py-2" variant="outline">
          Academic
        </Button>
        <Button className="rounded-md px-4 py-2" variant="outline">
          Creative
        </Button>
        <Button className="rounded-md px-4 py-2" variant="outline">
          Custom
        </Button>
        <Button className="rounded-md px-4 py-2" variant="outline">
          More
        </Button>
        <div className="ml-auto flex items-center">
          <label className="mr-2" htmlFor="synonyms-toggle">
            Synonyms:
          </label>
          <Switch id="synonyms-toggle" />
        </div>
      </div>
      <div className="flex">
        <div className="w-1/2 pr-2">
          <Textarea
            className="mb-4 h-96 w-full rounded-md border-2 dark:bg-[#262626] border-gray-300 p-4"
            placeholder="To rewrite text, enter or paste it here and press 'Paraphrase.'"
          />
          <div className="flex w-full items-center justify-between">
            <Button
              className="rounded-md px-4 py-2 text-gray-600 dark:text-gray-200 hover:bg-gray-100 hover:dark:bg-gray-800"
              variant="ghost"
            >
              <ClipboardCopyIcon className="mr-2 h-5 w-5" />
              Paste Text
            </Button>

            <Button className="rounded-md bt-gradient bg-green-500 px-6 py-2 text-white hover:bg-green-600">
              Paraphrase
            </Button>
          </div>
        </div>
        <div className="w-1/2 pl-2 flex flex-col gap-2 justify-between">
          <div className="h-96 w-full rounded-md border-2 border-gray-300" />
          <Button
            className="rounded-md self-end  px-4 py-2 text-gray-600 hover:dark:bg-gray-800 dark:text-gray-200 hover:bg-gray-100"
            variant="ghost"
          >
            <CopyIcon className="mr-2 h-5 w-5" />
            Try Sample Text
          </Button>
        </div>
      </div>
    </div>
  );
}

function CopyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>
  );
}

function ClipboardCopyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" />
      <path d="M16 4h2a2 2 0 0 1 2 2v4" />
      <path d="M21 14H11" />
      <path d="m15 10-4 4 4 4" />
    </svg>
  );
}
